custom_css: ... body: effect: [ shadow ] # [shadow, floatable, blur] highlight: language: true # show language of codeblock copy_btn: true text_align: # left, right, justify, center h1: left h2: left h3 : left h4: left p: justify note: # style for default note: {% note text %} icon: '\f054' color: ''
  
  
    
    
        
       
     
       
       
       
       
       
     
       
       